sudo: required
services:
  - docker

before_install:
  - docker build -t rsuriset/docker-react -f Dockerfile.dev . 
  
script:
  - docker run -e CI=true rsuriset/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket: elasticbeanstalk-us-east-2-576158128325
  bucker_path: docker-react
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

  
  
  
  
  
 
  

  
  
 